flutter build web \
  --dart-define=APPWRITE_PROJECT_ID=$APPWRITE_PROJECT_ID \
  --dart-define=APPWRITE_PROJECT_NAME=$APPWRITE_PROJECT_NAME \
  --dart-define=APPWRITE_PUBLIC_ENDPOINT=$APPWRITE_PUBLIC_ENDPOINT